apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: toraora
labels:
  - pairs:
      app.kubernetes.io/managed-by: kube-config
    includeSelectors: false
resources:
  - base
  - apps/passport
  - apps/webview
